# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_app', '0003_auto_20171019_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 20, 40, 10, 436336, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 20, 40, 10, 435653, tzinfo=utc)),
        ),
    ]
